version: '3.7'

services:
  db:
    image: postgres
    container_name: db
    env_file: .env
    ports:
      - "${DB_PORT}:5432"       
    environment:   
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}

    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  nestjs:
    build:
      context: .
    container_name: place-to-know-api
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/home/node
      - ./node_modules:/home/node/node_modules
    networks:
      - app-network
    command: npm run start:dev
    depends_on:
      - db

networks:
  app-network:
    driver: bridge